# Generated by Django 3.1.3 on 2020-12-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201201_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='photos',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='object',
            name='square',
            field=models.FloatField(verbose_name='Площадь'),
        ),
    ]
