# Generated by Django 3.1.3 on 2020-12-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201205_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('photos', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотографии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
